# Generated by Django 5.2.6 on 2025-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/%d', verbose_name='Изображение')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
